services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent-config:/config
      - streaming:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ./jellyfin-config:/config
      - tvshows:/data/tvshows
      - movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional https
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: true
volumes:
  streaming:
    driver: local
    external: true
    driver_opts:
      device: /srv/streaming
      o: bind
      type: local
  tvshows:
    driver: local
    external: true
    driver_opts:
      device: /srv/streaming/tvshows
      o: bind
      type: local
  movies:
    driver: local
    external: true
    driver_opts:
      device: /srv/streaming/movies
      o: bind
      type: local

